Repository Workiva/frugal, pull requests merged in 2018-08, with the labels that each got.

#1019 Update uuid version range for Dart 2
  lib/dart/pubspec.yaml
Labels: Merge Requirements Met

#1021 INFENG-6094 publish build artifacts
  Dockerfile
  scripts/smithy/smithy_python.sh
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready

#1024 INFENG-6008 upgrade versions of python nats libraries
  lib/python/requirements_dev_asyncio.txt
  lib/python/requirements_dev_tornado.txt
  lib/python/setup.py
  scripts/skynet/cross/setup_java.sh
  scripts/skynet/run_cross_skynet.sh
  skynet.yaml
  smithy.yaml
  test/integration/python/aio/__init__.py
  test/integration/python/aio/client.py
  test/integration/python/aio/server.py
  test/integration/tests.json
Labels: Hold Auto-Merge, Merge Requirements Met

#1022 New result args underscores
  compiler/generator/golang/generator.go
  test/expected/dart/variety/f_foo_service.dart
  test/expected/go/variety/f_foo_service.txt
  test/expected/go/variety/f_types.txt
  test/expected/go/variety_async/f_foo_service.txt
  test/expected/html/index.html
  test/expected/html/standalone/index.html
  test/expected/html/standalone/variety.html
  test/expected/html/variety.html
  test/expected/java/actual_base/nested_thing.java
  test/expected/java/actual_base/thing.java
  test/expected/java/boxed_primitives/FFoo.java
  test/expected/java/variety/EventsPublisher.java
  test/expected/java/variety/EventsSubscriber.java
  test/expected/java/variety/FFoo.java
  test/expected/java/variety_async/FFoo.java
  test/expected/python.asyncio/variety/f_Foo.py
  test/expected/python.tornado/variety/f_Foo.py
  test/expected/python/variety/f_Foo.py
  test/idl/variety.frugal
Labels: Merge Requirements Met

#1018 INFENG-6058 Dart: Generate hashCode getter for structs.
  compiler/generator/dartlang/generator.go
  test/expected/dart/actual_base/f_api_exception.dart
  test/expected/dart/actual_base/f_base_foo_service.dart
  test/expected/dart/actual_base/f_nested_thing.dart
  test/expected/dart/actual_base/f_thing.dart
  test/expected/dart/include_vendor/f_my_service_service.dart
  test/expected/dart/include_vendor/f_vendored_references.dart
  test/expected/dart/variety/f_awesome_exception.dart
  test/expected/dart/variety/f_event.dart
  test/expected/dart/variety/f_event_wrapper.dart
  test/expected/dart/variety/f_foo_args.dart
  test/expected/dart/variety/f_foo_service.dart
  test/expected/dart/variety/f_test_base.dart
  test/expected/dart/variety/f_test_lowercase.dart
  test/expected/dart/variety/f_testing_defaults.dart
  test/expected/dart/variety/f_testing_unions.dart
  test/expected/dart/vendor_namespace/f_item.dart
Labels: Hold Auto-Merge, Merge Requirements Met
