Repository Workiva/frugal, pull requests merged in 2019-04, with the labels that each got.

#1097 Allow setting the stop timeout for stopping a FNatsServer
  lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
  lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
Labels: Merge Requirements Met

#1100 Update jnats to 2.4.3
  lib/java/pom.xml
  test/integration/java/frugal-integration-test/pom.xml
Labels: Merge Requirements Met

#1098 Wait for unsubscribes to finish before shutting down executor service.
  lib/java/src/main/java/com/workiva/frugal/server/FNatsServer.java
  lib/java/src/test/java/com/workiva/frugal/server/FNatsServerTest.java
Labels: Merge Requirements Met, RM Ready

#1105 dart: Use const for simple constants
  compiler/generator/dartlang/generator.go
  test/expected/dart/actual_base/f_actual_base_dart_constants.dart
  test/expected/dart/variety/f_testing_defaults.dart
  test/expected/dart/variety/f_variety_constants.dart
  test/expected/dart/vendor_namespace/f_vendor_namespace_constants.dart
Labels: Merge Requirements Met

#1107 java: Explicitly handle NoHttpResponseException
  lib/java/src/main/java/com/workiva/frugal/transport/FHttpTransport.java
  lib/java/src/test/java/com/workiva/frugal/transport/FHttpTransportTest.java
Labels: Merge Requirements Met, RM Ready

#1109 dart: Fix constant set type parameter
  compiler/generator/dartlang/generator.go
  test/expected/dart/variety/f_variety_constants.dart
  test/expected/go/slim/f_types.go
  test/expected/go/variety/f_types.txt
  test/expected/gopherjs/variety/f_types.go
  test/expected/html/index.html
  test/expected/html/standalone/index.html
  test/expected/html/standalone/variety.html
  test/expected/html/variety.html
  test/expected/java/variety/varietyConstants.java
  test/expected/python.asyncio/variety/constants.py
  test/expected/python.tornado/variety/constants.py
  test/expected/python/variety/constants.py
  test/idl/variety.frugal
Labels: Merge Requirements Met, RM Ready

#1111 INFENG-8001 Fix build
  Dockerfile
  skynet.yaml
Labels: Merge Requirements Met, RM Ready

#1112 CPLAT-5534: Cast inner types on returned futures
  compiler/generator/dartlang/generator.go
  examples/dart/gen-dart/v1_music/lib/src/f_store_service.dart
  test/expected/dart/include_vendor/f_my_service_service.dart
  test/expected/dart/variety/f_foo_service.dart
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready
